version: '3.8'

services:
  functious:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
      - MONGODB=${MONGODB}
      - SENTRY_DSN=${SENTRY_DSN}
      - BOTID=${BOTID}
      - CDN=${CDN}
      - CDN_KEY=${CDN_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped